#!/usr/bin/env python3

import time

# If all nodes launched by apex_launchtest die before the tests are over, apex_launchtest treats that
# like a test failure.  To allow testing in this situation, apex_launchtest provides the empty_node
# which can be launched alongside the other nodes under test allowing them to terminate on their
# own without causing a test failure

if __name__ == "__main__":

    try:
        while True:
            time.sleep(1 * 60 * 60 * 24)
    except KeyboardInterrupt:
        pass
