#!/usr/bin/env python3

import sys
import time

import rclpy
import std_msgs.msg


def main():
    rclpy.init()
    node = rclpy.create_node("exception_node")

    try:
        time.sleep(0.5)
        raise Exception("Node had an exception") 
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()

if __name__ == "__main__":
    main()
