#!/usr/bin/env python3

import sys
import time

if __name__ == "__main__":

    print("Emulating Setup")
    time.sleep(1.0)
    print("Ready")

    if sys.argv[1:]:
        print("Called with arguments {}".format(sys.argv[1:]))

    try:
        print("Emulating Work")
        time.sleep(1.0)
        print("Done")
    except KeyboardInterrupt:
        pass
