#!/usr/bin/env python3

import sys

import rclpy
import std_msgs.msg

# This ROS node listens on the self_destruct topic and will die with a non-zero exit code
# once any message is received on that topic

def kaboom(msg):
    print(msg.data)
    sys.exit(1)

def main():
    rclpy.init()
    node = rclpy.create_node("dying_node")

    sub = node.create_subscription(
        msg_type=std_msgs.msg.String,
        topic="self_destruct",
        callback=kaboom
    )

    try: 
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()

if __name__ == "__main__":
    main()
