[pytest]
junit_family=xunit2
# Disable doctest modules temporarily to avoid ImportPathMismatchError with logging.handlers
# addopts = --doctest-modules
timeout=900
timeout_method=thread
pythonpath = test
